# Generated by Django 5.1.2 on 2024-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='None', max_length=100, unique=True),
        ),
    ]
