# Generated by Django 5.1.2 on 2024-12-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_category_product_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
